#-------------------------
# Database MySQL
#-------------------------

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/tender?serverTimezone=UTC&useSSL=false
  flyway:
    enabled: true
    schemas: tender
    locations: classpath:/db/migration
    baseline-on-migrate: true
server:
  port : 8081

